use_frameworks!

target 'PodMediastreamPlatformSDKiOS_Example' do
  pod 'PodMediastreamPlatformSDKiOS', :path => '../'

  target 'PodMediastreamPlatformSDKiOS_Tests' do
    inherit! :search_paths

    
  end
end
